// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
        int gt = 0;   // > 0.5
        int le = 0;   // <= 0.5

        for (int i = 0; i < N; i++) {
            double r = Math.random();
            if (r > 0.5) gt++;
            else le++;
        }

        System.out.println("> 0.5:  " + gt + " times");
        System.out.println("<= 0.5: " + le + " times");

        // Edge case: לא מחשבים Ratio כשהמכנה יהיה 0, או בכלל במקרה קיצון כמו בדוגמה
        if (gt != 0 && le != 0) {
            double ratio = (double) gt / (double) le;
            System.out.println("Ratio:  " + ratio);
        }
	}
}
